DROP TABLE FLAVORS;
DROP TABLE CONTAINERS;
DROP TABLE PRODUCTS;
DROP TABLE LOCATIONS;
DROP TABLE CUSTOMERS;

CREATE TABLE FLAVORS (
    FlavorID        number GENERATED by default on null as IDENTITY(START with 100000 INCREMENT by 1) PRIMARY KEY,
    FlavorName      varchar2(255),
    PricePerScoop   number(4,2)
);

CREATE TABLE CONTAINERS (
    ContainerID     number GENERATED by default on null as IDENTITY(START with 200000 INCREMENT by 1) PRIMARY KEY,
    ContainerName   varchar2(255),
    ContainerPrice  number(4,2),
    NumberOfScoops  number(2)
);

CREATE TABLE PRODUCTS (
    ProductID       number GENERATED by default on null as IDENTITY(START with 30000000 INCREMENT by 1) PRIMARY KEY,
    ProductName     varchar2(255) DEFAULT null,
    ProductPrice    number(6,2) DEFAULT null,
    FlavorID        number,
    ContainerID     number
);

CREATE TABLE LOCATIONS (
    LocationID      number GENERATED by default on null as IDENTITY(START with 30100000 INCREMENT by 1) PRIMARY KEY,
    LocationName    varchar2(255),
    Address         varchar2(255),
    City            varchar2(255),
    State           varchar2(50)
);

CREATE TABLE CUSTOMERS (
    CustomerID      number GENERATED by default on null as IDENTITY(START with 400000 INCREMENT by 1) PRIMARY KEY,
    FirstName       varchar2(255),
    LastName        varchar2(255),
    Email           varchar2(255),
    Phone           varchar2(255)
);

--FLAVORS-----------------------------------------------------------------------
INSERT into FLAVORS VALUES (null, 'Vanilla', 0.50);
INSERT into FLAVORS VALUES (null, 'Chocolate', 0.50);
INSERT into FLAVORS VALUES (null, 'Strawberry', 0.50);
INSERT into FLAVORS VALUES (null, 'Mint Chocolate Chip', 0.55);
INSERT into FLAVORS VALUES (null, 'Butter Pecan', 0.55);
INSERT into FLAVORS VALUES (null, 'Cookies N Cream', 0.55);
INSERT into FLAVORS VALUES (null, 'Pistachio', 0.55);
INSERT into FLAVORS VALUES (null, 'Chocolate Chip Cookie Dough', 0.55);
INSERT into FLAVORS VALUES (null, 'Coffee', 0.55);
INSERT into FLAVORS VALUES (null, 'Birthday Cake', 0.55);

--CONTAINERS--------------------------------------------------------------------
INSERT into CONTAINERS VALUES (null, 'Kids Cone', 0.12, 0.8);
INSERT into CONTAINERS VALUES (null, 'Small Cone', 0.14, 1);
INSERT into CONTAINERS VALUES (null, 'Medium Cone', 0.18, 2);
INSERT into CONTAINERS VALUES (null, 'Large Cone', 0.20, 3);
INSERT into CONTAINERS VALUES (null, 'Kids Cup', 0.14, 0.8);
INSERT into CONTAINERS VALUES (null, 'Small Cup', 0.18, 1);
INSERT into CONTAINERS VALUES (null, 'Medium Cup', 0.22, 2);
INSERT into CONTAINERS VALUES (null, 'Large Cup', 0.25, 3);
INSERT into CONTAINERS VALUES (null, 'Pint To-Go', 0.35, 4);
INSERT into CONTAINERS VALUES (null, 'Half Gallon To-Go', 0.45, 8);
INSERT into CONTAINERS VALUES (null, 'Gallon To-Go', 0.60, 16);

--PRODUCTS----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GetProductNameAndPrice
    (p_flavorid IN number, p_containerid IN number, p_name OUT varchar2, p_price OUT number)
AS
    v_flavor_name varchar2(255);
    v_container_name varchar2(255);
    v_container_price number;
    v_container_scoops number;
    v_flavor_price number;
BEGIN
    SELECT FlavorName, PricePerScoop into v_flavor_name, v_flavor_price
    FROM FLAVORS
    WHERE FlavorID = p_flavorid;
    
    SELECT ContainerName, ContainerPrice, NumberOfScoops into v_container_name, v_container_price, v_container_scoops
    FROM CONTAINERS
    WHERE ContainerID = p_containerid;
    
    p_name := v_container_name || ' of ' || v_flavor_name;
    p_price := 2.5 * ((v_flavor_price * v_container_scoops) + v_container_price);
END GetProductNameAndPrice;

CREATE OR REPLACE PROCEDURE PopulateProducts
AS
    CURSOR possible_products IS
        SELECT *
        FROM (SELECT FlavorID
                FROM FLAVORS)
        CROSS JOIN (SELECT ContainerID
                        FROM CONTAINERS);
                        
    v_product_name PRODUCTS.PRODUCTNAME%TYPE;
    v_product_price PRODUCTS.PRODUCTPRICE%TYPE;
    v_flavor_id number;
    v_container_id number;
    
BEGIN
    FOR current_product IN possible_products LOOP
        v_flavor_id := current_product.FlavorID;
        v_container_id := current_product.ContainerID;
        GetProductNameAndPrice(v_flavor_id, v_container_id, v_product_name, v_product_price);
        INSERT into PRODUCTS VALUES (null, v_product_name, v_product_price, v_flavor_id, v_container_id); 
    END LOOP;
END PopulateProducts;

EXEC POPULATEPRODUCTS;

--LOCATIONS---------------------------------------------------------------------

INSERT into LOCATIONS VALUES (null, 'Purdue Campus - PMU', '101 S Grant St', 'West Lafayette', 'IN');
INSERT into LOCATIONS VALUES (null, 'Chicago Loop', '213 S Michigan Ave', 'Chicago', 'IL');
INSERT into LOCATIONS VALUES (null, 'Ocean Beach - Outer Sunset', '1270 La Playa St', 'San Francisco', 'CA');

--CUSTOMERS---------------------------------------------------------------------
INSERT into CUSTOMERS 
VALUES (null,'Reagan','Puckett','r-puckett@outlook.ca','156-222-1458');
INSERT into CUSTOMERS 
VALUES (null,'Griffith','Fischer','gfischer@protonmail.edu','933-824-0389');
INSERT into CUSTOMERS 
VALUES (null,'Cathleen','Carney','c-carney@protonmail.com','519-699-1653');
INSERT into CUSTOMERS 
VALUES (null,'Callie','Greene','g.callie2289@protonmail.net','193-623-4573');
INSERT into CUSTOMERS 
VALUES (null,'Gannon','Prince','prince_gannon9709@yahoo.ca','306-686-1936');
INSERT into CUSTOMERS 
VALUES (null,'Jaime','Barrera','barrerajaime@aol.edu','298-984-4415');
INSERT into CUSTOMERS 
VALUES (null,'Azalia','Wells','awells3110@outlook.com','786-672-6847');
INSERT into CUSTOMERS 
VALUES (null,'Asher','Carney','c_asher@yahoo.net','887-252-1461');
INSERT into CUSTOMERS 
VALUES (null,'Anthony','Miller','miller_anthony4248@aol.ca','153-611-4164');
INSERT into CUSTOMERS 
VALUES (null,'Zeus','Britt','zbritt8865@protonmail.com','817-800-2352');
INSERT into CUSTOMERS 
VALUES (null,'Macey','Cook','c.macey450@icloud.com','898-889-2206');
INSERT into CUSTOMERS 
VALUES (null,'Emerson','Kramer','krameremerson9014@hotmail.edu','853-759-8647');
INSERT into CUSTOMERS 
VALUES (null,'Kerry','Todd','todd-kerry@outlook.com','732-479-0687');
INSERT into CUSTOMERS 
VALUES (null,'Adria','Anthony','a_adria4342@google.com','540-521-3358');
INSERT into CUSTOMERS 
VALUES (null,'Derek','Rosario','rosarioderek@outlook.net','523-714-4377');
INSERT into CUSTOMERS 
VALUES (null,'Cedric','Beasley','b_cedric@aol.couk','277-021-3221');
INSERT into CUSTOMERS 
VALUES (null,'Tanner','Harper','harper_tanner6742@outlook.edu','029-286-6563');
INSERT into CUSTOMERS 
VALUES (null,'Bell','Kelly','b.kelly5954@aol.org','525-951-0903');
INSERT into CUSTOMERS 
VALUES (null,'Walter','Short','w_short@protonmail.couk','540-855-6831');
INSERT into CUSTOMERS 
VALUES (null,'Cassidy','Sellers','s-cassidy@protonmail.net','322-745-6864');
INSERT into CUSTOMERS 
VALUES (null,'Malachi','Glass','glass-malachi1121@protonmail.org','476-234-3285');
INSERT into CUSTOMERS 
VALUES (null,'Hedda','Donaldson','donaldson-hedda6473@google.edu','280-374-7841');
INSERT into CUSTOMERS 
VALUES (null,'Cyrus','Suarez','s.cyrus@outlook.org','738-263-8792');
INSERT into CUSTOMERS 
VALUES (null,'Marshall','Solis','m_solis@hotmail.org','273-769-6487');
INSERT into CUSTOMERS 
VALUES (null,'Harriet','Buckner','buckner.harriet@google.edu','155-964-5732');
INSERT into CUSTOMERS 
VALUES (null,'Selma','Fulton','f_selma@google.ca','739-279-6457');
INSERT into CUSTOMERS 
VALUES (null,'Darrel','Sanders','d-sanders7839@hotmail.org','658-588-7343');
INSERT into CUSTOMERS 
VALUES (null,'Stone','Guzman','guzman_stone1018@icloud.ca','962-561-5468');
INSERT into CUSTOMERS 
VALUES (null,'Keaton','Knowles','knowles_keaton@protonmail.org','361-076-9867');
INSERT into CUSTOMERS 
VALUES (null,'Charles','Knowles','knowles.charles9188@google.couk','786-914-4168');
INSERT into CUSTOMERS 
VALUES (null,'Uriah','Hudson','hudsonuriah@protonmail.couk','188-531-6616');
INSERT into CUSTOMERS 
VALUES (null,'Garrison','Hooper','g-hooper@protonmail.edu','139-269-5247');
INSERT into CUSTOMERS 
VALUES (null,'Justin','Wilder','justinwilder7950@aol.edu','891-268-7772');
INSERT into CUSTOMERS 
VALUES (null,'Eliana','Lang','langeliana@icloud.ca','205-505-4261');
INSERT into CUSTOMERS 
VALUES (null,'Lisandra','Lancaster','lancaster.lisandra3809@google.net','110-413-4971');
INSERT into CUSTOMERS 
VALUES (null,'Alisa','Hartman','h_alisa9497@icloud.org','518-314-6026');
INSERT into CUSTOMERS 
VALUES (null,'Madeson','Mullen','madeson.mullen@protonmail.edu','038-842-1253');
INSERT into CUSTOMERS 
VALUES (null,'Gray','Blake','bgray@protonmail.com','227-743-6890');
INSERT into CUSTOMERS 
VALUES (null,'Melanie','Waller','wallermelanie4554@outlook.edu','047-157-4242');
INSERT into CUSTOMERS 
VALUES (null,'Megan','Kirby','kirby-megan6924@google.net','878-282-7644');
INSERT into CUSTOMERS 
VALUES (null,'Tobias','Moore','tmoore@yahoo.couk','256-714-3546');
INSERT into CUSTOMERS 
VALUES (null,'Melvin','Diaz','diazmelvin5767@hotmail.org','761-294-5798');
INSERT into CUSTOMERS 
VALUES (null,'Lawrence','Mccullough','mccullough.lawrence@google.ca','431-914-3474');
INSERT into CUSTOMERS 
VALUES (null,'Eliana','Newman','newman_eliana9249@outlook.net','475-334-4728');
INSERT into CUSTOMERS 
VALUES (null,'Rama','Nielsen','nielsen-rama2836@aol.couk','495-772-5273');
INSERT into CUSTOMERS 
VALUES (null,'Savannah','Lucas','lucas_savannah4960@icloud.com','635-746-1371');
INSERT into CUSTOMERS 
VALUES (null,'Keiko','David','davidkeiko4342@icloud.org','061-960-5612');
INSERT into CUSTOMERS 
VALUES (null,'Tucker','Browning','browningtucker3928@google.com','376-058-5848');
INSERT into CUSTOMERS 
VALUES (null,'Desirae','Webb','webb_desirae1501@google.net','713-434-7378');
INSERT into CUSTOMERS 
VALUES (null,'Solomon','Snow','s-snow3035@yahoo.ca','664-769-4878');
INSERT into CUSTOMERS 
VALUES (null,'Ava','Hines','a_hines3769@icloud.couk','125-225-8240');
INSERT into CUSTOMERS 
VALUES (null,'Eric','Young','y-eric5072@hotmail.com','624-752-3585');
INSERT into CUSTOMERS 
VALUES (null,'Guy','Rios','guy-rios@google.edu','395-324-2535');
INSERT into CUSTOMERS 
VALUES (null,'Alan','Adams','a-adams8768@yahoo.net','743-835-4586');
INSERT into CUSTOMERS 
VALUES (null,'Inez','Berry','i.berry6281@outlook.org','768-685-9577');
INSERT into CUSTOMERS 
VALUES (null,'Vera','Bartlett','vera.bartlett@icloud.ca','332-810-4870');
INSERT into CUSTOMERS 
VALUES (null,'Wallace','Wilson','wallace_wilson@aol.ca','114-824-9820');
INSERT into CUSTOMERS 
VALUES (null,'Alyssa','Cabrera','cabrera_alyssa1642@hotmail.ca','546-979-0668');
INSERT into CUSTOMERS 
VALUES (null,'Hyatt','Cohen','cohen-hyatt5665@google.org','583-755-2855');
INSERT into CUSTOMERS 
VALUES (null,'Rina','Dunn','dunn.rina@hotmail.org','316-189-6014');
INSERT into CUSTOMERS 
VALUES (null,'Vivien','Ramos','v_ramos8076@icloud.org','794-227-6879');
INSERT into CUSTOMERS 
VALUES (null,'Sasha','Battle','s.battle@outlook.ca','135-312-7798');
INSERT into CUSTOMERS 
VALUES (null,'Jackson','Prince','jackson.prince3318@icloud.com','063-478-5554');
INSERT into CUSTOMERS 
VALUES (null,'Leilani','Christian','christian_leilani6021@hotmail.net','359-366-6843');
INSERT into CUSTOMERS 
VALUES (null,'Dolan','Baxter','b_dolan4539@yahoo.couk','069-580-2028');
INSERT into CUSTOMERS 
VALUES (null,'Aurora','Lamb','lamb.aurora1573@icloud.edu','428-923-6442');
INSERT into CUSTOMERS 
VALUES (null,'Yen','Fields','y_fields6661@aol.couk','873-886-8071');
INSERT into CUSTOMERS 
VALUES (null,'Chanda','Mccormick','mccormick.chanda@hotmail.couk','584-142-5442');
INSERT into CUSTOMERS 
VALUES (null,'Raven','Heath','raven_heath3873@hotmail.net','241-203-3045');
INSERT into CUSTOMERS 
VALUES (null,'Daphne','Hess','daphne-hess8745@aol.net','259-523-6383');
INSERT into CUSTOMERS 
VALUES (null,'Kim','Blair','blair-kim@hotmail.com','405-072-8657');
INSERT into CUSTOMERS 
VALUES (null,'Stacy','Holland','s_holland8647@aol.org','738-841-4743');
INSERT into CUSTOMERS 
VALUES (null,'Myles','Atkinson','matkinson6250@protonmail.edu','028-482-2382');
INSERT into CUSTOMERS 
VALUES (null,'Mannix','Duran','dmannix@protonmail.com','342-538-4952');
INSERT into CUSTOMERS 
VALUES (null,'Armand','Bishop','a-bishop@outlook.com','101-813-4885');
INSERT into CUSTOMERS 
VALUES (null,'Xanthus','Love','x_love@icloud.com','373-771-7312');
INSERT into CUSTOMERS 
VALUES (null,'Barbara','Hopper','b_hopper@icloud.ca','818-683-3376');
INSERT into CUSTOMERS 
VALUES (null,'Gary','Watkins','watkins-gary7848@outlook.ca','869-476-6276');
INSERT into CUSTOMERS 
VALUES (null,'Deacon','Henry','deacon-henry7359@icloud.org','892-184-6958');
INSERT into CUSTOMERS 
VALUES (null,'Joshua','Whitney','whitney.joshua962@aol.ca','156-561-4018');
INSERT into CUSTOMERS 
VALUES (null,'Julian','Vinson','v_julian9075@icloud.net','103-373-1126');
INSERT into CUSTOMERS 
VALUES (null,'Selma','King','s.king@icloud.edu','863-596-2752');
INSERT into CUSTOMERS 
VALUES (null,'Courtney','Lawrence','lawrencecourtney6454@hotmail.com','203-974-9316');
INSERT into CUSTOMERS 
VALUES (null,'Wyatt','Hopkins','w_hopkins7873@aol.net','579-278-7557');
INSERT into CUSTOMERS 
VALUES (null,'Martin','Sharp','martin.sharp9629@hotmail.edu','777-535-5584');
INSERT into CUSTOMERS 
VALUES (null,'Roanna','Patterson','roanna.patterson@hotmail.edu','213-814-5844');
INSERT into CUSTOMERS 
VALUES (null,'Raymond','Boyle','b-raymond3861@yahoo.org','467-600-1144');
INSERT into CUSTOMERS 
VALUES (null,'Lewis','Mcneil','mcneillewis@yahoo.ca','488-223-7455');
INSERT into CUSTOMERS 
VALUES (null,'Vladimir','Russo','vladimir.russo1172@yahoo.com','897-805-7574');
INSERT into CUSTOMERS 
VALUES (null,'Clare','Orr','corr@hotmail.edu','702-451-4471');
INSERT into CUSTOMERS 
VALUES (null,'MacKensie','Watkins','wmackensie@icloud.ca','372-717-7312');
INSERT into CUSTOMERS 
VALUES (null,'Miranda','Hunt','h_miranda9796@outlook.edu','121-089-1150');
INSERT into CUSTOMERS 
VALUES (null,'Dane','Simon','dsimon7483@google.edu','277-667-4727');
INSERT into CUSTOMERS 
VALUES (null,'Warren','Anthony','warren-anthony@hotmail.org','925-802-9137');
INSERT into CUSTOMERS 
VALUES (null,'Channing','Stewart','s-channing@protonmail.org','931-663-5164');
INSERT into CUSTOMERS 
VALUES (null,'Indira','Frye','frye-indira@google.couk','583-502-8260');
INSERT into CUSTOMERS 
VALUES (null,'Walker','Ballard','ballardwalker@outlook.edu','922-804-5000');
INSERT into CUSTOMERS 
VALUES (null,'Martina','Bradford','bradford.martina9208@google.couk','080-845-5718');
INSERT into CUSTOMERS 
VALUES (null,'Lucy','Weber','l-weber@icloud.couk','037-596-4264');
INSERT into CUSTOMERS 
VALUES (null,'Tiger','Stuart','t.stuart6044@aol.ca','566-857-6932');
